pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }

        maven {
            name "kernelpanic"
            url "https://repo.kernelpanicsoft.net/maven/releases"
        }
    }

}



plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

